[2024-03-07T00:58:51.515+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Carregamento_dos_dados_analitico manual__2024-03-07T00:58:47.792435+00:00 [queued]>
[2024-03-07T00:58:51.533+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Carregamento_dos_dados_analitico manual__2024-03-07T00:58:47.792435+00:00 [queued]>
[2024-03-07T00:58:51.534+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-07T00:58:51.614+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Carregamento_dos_dados_analitico> on 2024-03-07 00:58:47.792435+00:00
[2024-03-07T00:58:51.623+0000] {standard_task_runner.py:60} INFO - Started process 2925 to run task
[2024-03-07T00:58:51.628+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Carregamento_dos_dados_analitico', 'manual__2024-03-07T00:58:47.792435+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmpo15mj9mo']
[2024-03-07T00:58:51.631+0000] {standard_task_runner.py:88} INFO - Job 66: Subtask Carregamento_dos_dados_analitico
[2024-03-07T00:58:51.827+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Carregamento_dos_dados_analitico manual__2024-03-07T00:58:47.792435+00:00 [running]> on host 4fca1e22de4a
[2024-03-07T00:58:52.158+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Carregamento_dos_dados_analitico' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:58:47.792435+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-07T00:58:47.792435+00:00'
[2024-03-07T00:58:53.418+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-07T00:58:53.435+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Extraçao_de_dados_do_linkedin, task_id=Carregamento_dos_dados_analitico, execution_date=20240307T005847, start_date=20240307T005851, end_date=20240307T005853
[2024-03-07T00:58:53.528+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T00:58:53.560+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
